import React from 'react';
import Nav from '../navbar/index';
import Disclaimer from '../footer/disclaimer';
import '../../section/terms.scss';

export default props => {
  return (
    <div className='main-container conditions'>
      <Nav />
      <h1>Terms & Conditions</h1>
      <p>Updated as of March 15, 2019</p>

      <p><span className='green'>Fund That Film</span> (“Company,” “we” or “us”) welcomes you.  We provide the website at <span className='green'>www.fundthatfilm.com</span> (the “Site”) to you, subject to the terms and conditions contained in this Terms of Service (this “TOS”).  This TOS governs the relationship between Company and you, the user of the Site.  </p>

      <p className='green'>1. Legally Binding Agreement; Changes to TOS.</p> 

      <p><span className='green'>1.1</span> Please read this TOS carefully as it contains legal obligations.  You agree that by registering for or using our Services (defined in Section 2 below), or by accessing or using our Site, you are entering into a legally binding agreement with Movie Funding.  If you are using or accessing the Services or Site on behalf of your employer, another individual or an entity, such as a corporate entity, trust, partnership or other organization (collectively, “Authorizing Party”), you represent that you are duly authorized by such Authorizing Party to enter into this TOS on behalf of such Authorizing Party (and “you” as used in this TOS refers both to you individually and to the Authorizing Party).  You also represent to Movie Funding that you are of the legal age to form a binding agreement with us and that you are not a person or entity barred from accessing or using the Site under the laws of the United States or other applicable jurisdiction.  By clicking “Apply” at the time or after you register with us, you acknowledge that you have read and understood the terms and conditions of this TOS and that you agree to be bound by all of its provisions, that you also consent to use electronic signatures, and that you acknowledge your click of the “Apply” button as one such signature.  If you do not want to register for an account with us, or you do not agree to any terms of this TOS, do not click “Apply” and do not access or use the Services or Site.</p>  

      <p><span className='green'>1.2</span> We reserve the right to update or make changes to this TOS from time to time in our sole discretion, and we may notify you of changes by any reasonable means, including without limitation, by notifying you through the email you provide us in your User Profile (defined in Section 2) or by posting the revised version of this TOS on the Site, which changes will become effective immediately upon the transmission of such email or posting on the Site, whichever occurs first.  You can determine when this TOS was last revised by referring to the “Updated” legend at the top of this TOS.  Please return to this page periodically to ensure familiarity with the most current version of this TOS.  Your continued access or use of the Services or Site after any changes to this TOS shall constitute your agreement and consent to such changes.  You agree that your use, access and purchase of any Services may be subject to any additional posted guidelines, rules, terms and conditions applicable to such Services (collectively, “Policies”), which are hereby incorporated by reference into this TOS.  In the event that any terms or conditions of such Policies contradict or are inconsistent with the terms and conditions of this TOS, such Policies will govern and prevail solely with respect to the specified Services to which they apply.</p>

      <p className='green'>2. Definitions.</p>

      <p><span className='green'>2.1</span> “Accredited Investor” has the meaning ascribed thereto by the SEC in Rule 501 of Regulation D (as amended from time to time) under the U.S. Securities Act of 1933 (the “Act”), or such other rule as may succeed Rule 501 from time to time.  For informational purposes only, as of the date hereof, the “Accredited Investor” is defined as:</p>

      <p><span className='green'>(i)</span> Any bank as defined in section 3(a)(2) of the Act, or any savings and loan association or other institution as defined in section 3(a)(5)(A) of the Act whether acting in its individual or fiduciary capacity; any broker or dealer registered pursuant to section 15 of the Securities Exchange Act of 1934; any insurance company as defined in section 2(a)(13) of the Act; any investment company registered under the Investment Company Act of 1940 or a business development company as defined in section 2(a)(48) of that Act; any Small Business Investment Company licensed by the U.S. Small Business Administration under section 301(c) or (d) of the Small Business Investment Act of 1958; any plan established and maintained by a state, its political subdivisions, or any agency or instrumentality of a state or its political subdivisions, for the benefit of its employees, if such plan has total assets in excess of $5,000,000; any employee benefit plan within the meaning of the Employee Retirement Income Security Act of 1974 if the investment decision is made by a plan fiduciary, as defined in section 3(21) of such act, which is either a bank, savings and loan association, insurance company, or registered investment adviser, or if the employee benefit plan has total assets in excess of $5,000,000 or, if a self-directed plan, with investment decisions made solely by persons that are accredited investors;</p>

      <p><span className='green'>(ii)</span> Any private business development company as defined in section 202(a)(22) of the Investment Advisers Act of 1940;</p>

      <p><span className='green'>(iii)</span> Any organization described in section 501(c)(3) of the Internal Revenue Code, corporation, Massachusetts or similar business trust, or partnership, not formed for the specific purpose of acquiring the securities offered, with total assets in excess of $5,000,000;</p>

      <p><span className='green'>(iv)</span> Any director, executive officer, or general partner of the issuer of the securities being offered or sold, or any director, executive officer, or general partner of a general partner of that issuer;</p>

      <p><span className='green'>(v)</span> Any natural person whose individual net worth, or joint net worth with that person's spouse, at the time of his purchase exceeds $1,000,000;</p>

      <p><span className='green'>(vi)</span> Any natural person who had an individual income in excess of $200,000 in each of the two most recent years or joint income with that person's spouse in excess of $300,000 in each of those years and has a reasonable expectation of reaching the same income level in the current year;</p>

      <p><span className='green'>(vii)</span> Any trust, with total assets in excess of $5,000,000, not formed for the specific purpose of acquiring the securities offered, whose purchase is directed by a sophisticated person as described in Rule 506(b)(2)(ii); and</p>

      <p><span className='green'>(viii)</span> Any entity in which all of the equity owners are accredited investors.</p>

      <p><span className='green'>2.2</span> “Code of Conduct” means the rules governing the conduct by Users when using or accessing any of the Services or Site, as prescribed by Movie Funding from time to time.  A copy of the current Code of Conduct can be found here, the contents of which are hereby incorporated by reference into this TOS.</p>

      <p><span className='green'>2.3</span> “Company Person” means any employee, officer, director, agent, representative or affiliate of the Company.</p>

      <p><span className='green'>2.4</span> “Confidential Information” means all Content owned or controlled by a User made available on the Services or Site that is marked or designated by such User or Movie Funding as “confidential,” that is disclosed under circumstances indicating its confidential nature, or otherwise would be known to be confidential by a reasonable person.  If a User, in the Company's reasonable determination, ceases to treat as confidential such User’s Content designated by such User as Confidential Information, or if such Content is disclosed by such User to a third party without any obligations of confidentiality, or if such Content becomes public information through no fault of any receiving User, then such Content shall no longer be deemed Confidential Information for the purposes of this TOS.  Notwithstanding anything in the preceding sentence, any and all information disclosed under the FIRSTLOOK feature (the description of which can be found here) of the Services and Site shall be deemed Confidential Information.</p>

      <p><span className='green'>2.5</span> “Content” means (a) images, text, messages, works of authorship, photographs, graphics, comments, suggestions, video, audio, or other material uploaded, downloaded, appearing or otherwise made available on or through the Services or the Site; and (b) personally identifiable information, data and other information uploaded, downloaded, appearing or otherwise made available on or through the Services or the Site.</p>

      <p><span className='green'>2.6</span> “Eligible User Profile” means the profile created by the User which may contain the User’s email address, the password used to access the User’s account, payment information, and any other information the Company may require to complete or maintain your registration of an account.</p>   

      <p><span className='green'>2.7</span> “Filmmaker” means a User who represents one or more film projects through the Services or Site and may (or may not) be interested in procuring investor interest for such film project(s) through the Services or Site.</p>

      <p><span className='green'>2.8</span> “Investor” means a User who has indicated an interest in finding investment opportunities offered by Filmmakers through the Services or Site.</p>

      <p><span className='green'>2.9</span> “Privacy Policy” means Movie Funding's policy on how Movie Funding collects, uses, discloses and manages information and data collected about Users of the Services and Site, which policy may be modified by Movie Funding from time to time.  A copy of the current Privacy Policy can be found here.</p>

      <p><span className='green'>2.10</span> “Prohibited Activity” means one or more activities designated by Movie Funding as prohibited from time to time in its sole and absolute discretion.  Without limiting the foregoing, the following will be deemed Prohibited Activities:</p>

      <p><span className='green'>(i)</span> The modification, adaptation, disassembly, de-compilation, translation, reverse engineering or other attempt to discover the source code or structure, sequence and organization of the Services or Site (except where the foregoing is permitted by applicable local law notwithstanding such restrictions, and then only to the extent that such intended activities are disclosed in advance in writing to us);</p>

      <p><span className='green'>(ii)</span> The use of Services or Site in any manner that could damage, disable, overburden, impair or otherwise interfere with or disrupt the Services, Site or any networks or security systems of Company or its service providers, or otherwise interfere with other Users’ use of the Services or Site;</p>

      <p><span className='green'>(iii)</span> The removal, obscuring or changing of any copyright, trademark, hyperlink or other proprietary rights notices contained in or on the Services, Site or any Content;</p>

      <p><span className='green'>(iv)</span> The submission of any Content or material that expresses or implies that such Content or material is sponsored or endorsed by the Company;</p>

      <p><span className='green'>(v)</span> The use of the Services or Site to violate the security of any computer network or to transfer or store illegal material; or</p>

      <p><span className='green'>(vi)</span> The use of the Services or the delivery of any Content in violation of any applicable law, including the securities laws, intellectual property laws, right of privacy or publicity laws and any laws of any jurisdiction (including that of the United States of America) applicable to you or Movie Funding.</p>

      <p><span className='green'>2.10</span> “SEC” means the U.S. Securities and Exchange Commission, and/or any successor entity or entities thereto.</p>

      <p><span className='green'>2.11</span> “Services” means any and all services made available on the Site, including any information, features, functionality and applications offered on the Site from time to time.  Access to certain Services may be based on the type of subscription you have purchased and/or based on the designation of your user type (i.e. Investor, Filmmaker or other user type).</p>

      <p><span className='green'>2.12</span> “User” means any user of the Services and/or Site.</p>

      <p className='green'>3. Movie Funding Services, Related Undertakings and Limitations.</p> 

      <p><span className='green'>3.1</span> Right to use the Services.  Subject to your acceptance of, and compliance with, this TOS, we grant you a non-exclusive, revocable, non-assignable, non-sublicenseable, non-transferable right to access and use the Services to which you have subscribed and the Site.  The Services and Site are protected by copyright, trademark, and other laws of both the United States and foreign countries.  Except as expressly provided herein, nothing in this TOS gives you a right to use our trademarks, trade names, service marks, logos, domain names, or other brand features.  Movie Funding and its licensors reserve all rights not expressly granted in this TOS.</p>

      <p><span className='green'>3.2</span> Restrictions and Obligations.  You agree that in accessing and using the Services and Site, you agree that you will:</p>

      <p><span className='green'>(i)</span> not modify, alter, adapt or create a derivative work of any Content of another User, the Services or the Site;</p>

      <p><span className='green'>(ii)</span> attribute the Site as the source of any information which you obtain from the Site, with such attribution in the form of a human and machine-followable link (a tag) linking back to the page on the Site displaying the original Content which contains such information (or if the original page is not accessible to the recipient or viewer of the information without logging in through an account with us, then you will attribute the Site generally as the source of such information).  For purposes of clarity, you shall not have the right to use or disclose any Confidential Information in breach of your confidentiality obligations in Sections 4.2;</p> 

      <p><span className='green'>(iii)</span> upon request by Movie Funding, make a reasonable effort to update your Content on the Site and/or the Services to the most updated version (and we will similarly make a reasonable effort to update any of your Content on the Site upon our receipt of your written request);</p>

      <p><span className='green'>(iv)</span> upon request, either by Movie Funding or by a User who provided the Content, make a reasonable attempt to permanently delete, destroy and erase any Content that has been deleted from the Site (and require that any party to whom such Content has been provided, through multiple tiers, do to the same);</p>

      <p><span className='green'>(v)</span> will not use the Services or Site, or display any results, Content or information from the use of the Services or Site in any way to compete with Movie Funding, the Services or the Site;</p>

      <p><span className='green'>(vi)</span> will not sublicense, transfer, share, lend (via a service bureau or otherwise), distribute or resell to any third party your right to access or use the Services or Site (or any portion thereof);</p>

      <p><span className='green'>(vii)</span> will not use any data mining features, robots, spiders or similar data gathering and extraction tools in your use of the Services or Site to retrieve, index, “scrape,” “data mine,” or in any way gather content or data from the Services or Site, or otherwise circumvent the navigational structure or presentation of the Services or Site; and</p>

      <p><span className='green'>(viii)</span> will not circumvent, disable, override or otherwise interfere with any security-related features of the Services or Site, or any other features that prevent or restrict use, copying, data mining or otherwise or enforce the limitations on the use of the Services or Site.</p>

      <p><span className='green'>3.3</span> License to Your Content.  By uploading or otherwise providing any Content through your use of the Services or Site, whether through your account with us or otherwise, you hereby grant to Movie Funding a non-exclusive, non-transferable (except as permitted in Section 10.8) royalty-free, fully paid-up, irrevocable, worldwide right and license to use, display, perform, exhibit, modify, reproduce and make available such Content through the Services and Site to other Users during the term of this TOS.  After the term of this TOS, we shall have the right to maintain a copy of such Content for archival purposes and in order to enforce our rights under this TOS.</p>

      <p><span className='green'>3.4</span> Ownership.  Subject to the licenses granted in Section 3.3, as between Movie Funding and you, you shall exclusively own and retain all right, title and interest (including all intellectual and proprietary rights) in and to your Content.  As between you and Movie Funding, Movie Funding shall exclusively own and retain all right, title and interest (including all intellectual and proprietary rights) in and to the Services and Site, including all Content (other than your Content) and other materials appearing therein.  Movie Funding shall also own any and all metadata related to your Content generated by Movie Funding’s Services, Site and systems.</p>

      <p><span className='green'>3.5</span> Subscriptions; Fees.</p>

      <p><span className='green'>(i)</span> In order to use and access certain portion of the Services and Site, you will be required to purchase subscriptions which may be offered with a monthly, annual or other term.  We may offer different levels of subscriptions, which provide different levels of access to the features of the Services and Site. The term of your subscription will commence on the date you purchase such subscription.</p> 

      <p><span className='green'>(ii)</span> For monthly subscriptions, payment will be initiated on a monthly basis and will be paid in advance or on the first day of each such month of your subscription term.  For annual subscriptions, you will be charged for the annual term of your subscription at the time you purchase such subscription.  You hereby authorize us to collect from your payment method all outstanding fees and charges for your account.  If any fees and charges are not paid by the due date, Movie Funding may suspend or terminate your access to the Services and Site, without notice to you, until all amounts due are paid.  Additionally, any fees and charges which are not paid by the due date are subject to a late charge of one percent (1%) (or the maximum amount permitted by applicable law, whichever is lower) for each month, or fraction thereof, until the full amount due is paid in full.  You are responsible to pay all fees and charges for your subscriptions, and except as described in this TOS, any suspension, termination or disconnection of the Services or Site does not relieve you of the obligation to pay such fees.</p>

      <p><span className='green'>(iii)</span> You may cancel your monthly subscription by providing written notice to us of such cancellation.  Your subscription will terminate at the end of the month during which you cancelled, and you will be charged the applicable subscription fee for such month.  You may cancel your annual subscription by providing written notice to us of such cancellation, which notice must be received by us during the first 180 days of your annual subscription.  Upon such cancellation, your subscription will terminate at the end of such 180-day period and you will be entitled to a refund of fifty percent (50%) of the annual subscription fees actually paid to us, less any amounts owed to us.  You will not be entitled to any refund of the subscription fee if you elect to cancel your annual subscription after the first 180 days thereof.</p>  

      <p><span className='green'>(iv)</span> If we terminate your subscription without a stated reason, you will only be responsible for the applicable subscription fees, on a pro-rata basis, through the date of the termination of your subscription.  If we terminate your subscription for a stated reason, then you will be responsible for the applicable subscription fees through the end your subscription term.  “Stated reasons” include the following: (a) we have determined, in our sole discretion, that you have misused the Services or the Site, engaged in suspected fraudulent or illegal activity, engaged in other activity that adversely affects the Services, Site or our network, or other Users’ ability to use the Services or Site; or (b) you have breached this TOS.  You understand that Company reserves the right to monitor all uses of the Services and Site, and your compliance with this TOS.  Your subscription may be resumed after we have terminated your subscription for a stated reason, but the original term thereof shall not be extended.</p>

      <p><span className='green'>(v)</span> Other features of the Services or Site may be subject to a fee, such as a submission fee for submitting a project to us. All such fees are non-refundable.</p>

      <p><span className='green'>3.6</span> Accredited Investors.  We will require all new or prospective Users of Movie Funding who identify themselves as Investors to execute an Accredited Investor Questionnaire.  We have created a questionnaire that is designed to make (prospective) Users review whether they truly are accredited and sophisticated, but we do not verify the representations they make or whether such Users would be deemed accredited under applicable state, federal or international securities laws or other laws.  We have also designed the Site so that an Investor is not intended to be introduced to any Filmmaker whose capital raising activities were in process when that Investor becomes a member of Movie Funding, but we cannot guarantee that our design is foolproof, or that Investors who learn about a Filmmaker's business through Movie Funding will not find another way to be introduced to such Filmmaker.</p>

      <p><span className='green'>3.7</span> Display Filmmakers' Content and Allow Communications with Investors Only as Instructed by the Filmmaker/Investor. When you create an account with Movie Funding, and at any time thereafter, you will be able to set a variety of filters that are intended to control who is able to see your Confidential Information and what information of other Users will be accessible by you.  We will make commercially reasonable efforts not to intentionally violate such filters: provided, however, that we do not guarantee or warranty:</p>

      <p><span className='green'>(i)</span> that there will never be a software bug or a hacker attack that will allow unauthorized viewing of material or unsolicited contacts to occur; or</p>

      <p><span className='green'>(ii)</span> that any other User whom you have given access to Confidential Information will not violate the conditions of confidentiality that you and / or the Company have imposed on such User and such Confidential Information.</p>

      <p><span className='green'>3.8</span> Reservations and Limitations.  Without limiting any right, privilege, limitation or reservation contained elsewhere in this TOS and benefiting the Company, the Company reserves the following rights: </p>  

      <p><span className='green'>(i)</span> Movie Funding reserves the right, but is not required, to monitor, modify, suppress, delete or control the Content posted via the Services or the Site, and to take any action with respect to such Content at any time and without notice to you or other Users.  Our failure to exercise that right, however, does not give you or any other party any right to make a claim against Movie Funding.</p>

      <p><span className='green'>(ii)</span> Movie Funding reserves the right, at any time and from time to time, temporarily or permanently, in whole or in part, to modify, suspend or discontinue the Services or Site in any way and at any time, with or without notice to you.  You agree that any notices to you will be deemed provided to you and effective on the date of posting on the Site or on the day of email to the email account we have on file for your account, whichever occurs earlier.  You agree that (a) Movie Funding shall not be liable to you or to any third party for any modification, suspension or discontinuance of the Services or Site, in whole or in part, and (b) your continued use of the Services or site after any changes to the Services or Site have been implemented will be deemed your acceptance of such changes.  In the event that the Services are discontinued, you will be responsible for the applicable subscription fees, on a pro-rata basis, through the date of the discontinuance of such Services.</p>   

      <p><span className='green'>(iii)</span> Movie Funding reserves the right to terminate your access to the Services or Site without notice and, in the event that you have violated this TOS, to pursue additional remedies available to Movie Funding at law or in equity.</p>

      <p><span className='green'>(iv)</span> Movie Funding reserves the right to delete your account for any reason or for no reason at all, and if Movie Funding deletes your account you will lose all access to any information, connections or other features that may have value to you that may have been associated with your account.</p>

      <p><span className='green'>(v)</span> Movie Funding reserves the right to refuse registration of, or cancel, your account in its discretion for any reason or for no reason.  In addition, Movie Funding reserves the right at all times (but will not have an obligation) to remove or refuse to distribute any Content through the Services or Site and to terminate Users or reclaim Usernames.  Movie Funding also reserves the right to access, read, preserve, and disclose any information as it reasonably believes is necessary to: (1) comply with any applicable law, regulation, legal process or governmental request; (2) enforce this TOS (including investigation of potential violations hereof); (3) detect, prevent, or otherwise address fraud, security or technical issues; (4) respond to User support requests; and/or (5) protect the rights, networks, property or safety of Movie Funding, its Users and the public.</p>

      <p><span className='green'>(vi)</span> Without limiting the generality of the foregoing, you specifically acknowledge that Movie Funding has the right to terminate or limit your account for any reason or no reason at all.  Any Content that has been uploaded through the Services or Site may be deleted at any time without notice to you.  Movie Funding shall have no liability to any person for any claim based upon its termination of an account or disabling of access to or removal of any Content, including material it believes, in its sole discretion to violate this TOS, regardless of whether the material ultimately is determined to be infringing or otherwise prohibited, and regardless of whether such termination or disabling has the effect of reducing the value of any Content or opportunities that might otherwise have been available to you.  By using the Services or Site, you agree that notice to you through an email to the email address you provided in your profile constitutes reasonable efforts to notify you of any removal or disabling if such notice is required.</p>

      <p><span className='green'>(vii)</span> We are not obligated to display your Content to any other User, nor are we obligated to introduce you to any Filmmaker or Investor.</p>

      <p><span className='green'>(viii)</span> We are not responsible for conducting due diligence on the Users you meet through the Services or Site.  Should we conduct due diligence on one or more Users, this does not change the meaning or effect of the immediately foregoing sentence, nor are we responsible or can be held liable for the outcome of any such due diligence.</p>

      <p><span className='green'>(ix)</span> We are not responsible for verifying that any Investor is accredited or otherwise authorized or appropriate to invest in your project, or for determining whether any use of Movie Funding constitutes a general solicitation of securities under U.S. law or the laws of any state or other jurisdiction, including foreign jurisdictions.</p>

      <p><span className='green'>(x)</span> We do not recommend any films or other ventures for investment or endorse their fitness for investment, verify the information on the Site or in our emails; and we do not claim that any Content provided by Users or the Company is accurate, complete and not misleading.</p>

      <p><span className='green'>(xi)</span> We are not obligated to maintain the confidentiality of any Content you give us, other than with respect to Confidential Information, and with respect to Confidential Information, we are not obligated to protect it other than by designating it as such and putting in place reasonable technological measures that we have determined in good faith to secure the confidentiality of such Confidential Information.  However, we cannot guarantee complete security; specifically, we cannot and do not guarantee that our measures will prevent all unauthorized access and use of Confidential Information, nor do we guarantee that the technology will never fail.</p>

      <p><span className='green'>(xii)</span> We have no obligation to monitor or enforce any intellectual property rights that may be associated with Content you provide to us.</p>

      <p><span className='green'>(xiii)</span> In the event that we invest in any film at any stage of development, we are not obligated to make that investment opportunity available to anyone else.</p>

      <p><span className='green'>(xiv)</span> The Company does not endorse the Content found through the Services, the Site or external sites that may be linked to or from the Site and, therefore, the Company specifically disclaims any responsibility with regard thereto.</p>

      <p><span className='green'>(xv)</span> The Company has no obligation to accept, display, review, monitor, or maintain any Content submitted by Users, User forum posts, commentary, ratings or compliments.  We have the right to delete, suppress and modify Content or comments from the Services or Site without notice for any reason at any time.  The Company may move, re-format, edit, alter, distort, remove or refuse to exploit Content or comments without notice to you and without liability.  Notwithstanding the foregoing rights, the Company reserves the right to treat both Content and comments as Content stored at the direction of Users for which the Company will not exercise editorial control except as required to enforce the rights of third parties and applicable Content restrictions below when violations are brought to the Company's attention.</p>

      <p><span className='green'>(xvi)</span> The Services or Site may contain or deliver advertising and sponsorships.  Advertisers and sponsors are, but the Company is not, responsible for ensuring that material submitted for inclusion is accurate and complies with applicable laws. We are not responsible for the illegality or any error, inaccuracy or problem in the advertiser's or sponsor's Content.</p>

      <p><span className='green'>3.9</span> Compliance with Law.  In using and accessing the Site and Services, you agree to comply with all applicable federal, state, local and international laws and regulations, including privacy laws, and export and import laws, regulations, orders or other restrictions administered by the United States Commerce Department's Bureau of Export Administration, the United States Department of Treasury's Office of Foreign Assets Control or any other applicable government agency. </p>

      <p className='green'>4. Your Obligations.</p>

      <p><span className='green'>4.1</span> Requirements of Membership.  You have the right, authority, and capacity to enter into this TOS on your own behalf and on behalf of any Authorizing Party on whose behalf, or in whose interest, you are acting and to abide by all of the terms and conditions contained herein, and that if any aspect of your access or use of the Services or Site violates any provisions of law to which you or the Services or Site are subject, you will cease all access and use of the Services and Site and close your account if deemed necessary or desirable by Movie Funding.</p>

      <p><span className='green'>4.2</span> Confidentiality Obligations.</p>

      <p><span className='green'>(i)</span> In accessing and using the Services and Site, based on the type of subscription you have purchased and/or based on the designation of your user type, you may be given access to the Confidential Information of one or more other Users (“Disclosers”).  You agree (a) to hold the Confidential Information of Disclosers in strict confidence and to take all necessary precautions (but in no event less than reasonable care) to protect such Confidential Information from unauthorized disclosure, access or use; (b) not to disclose or provide access to any such Confidential Information or any information derived therefrom to any person other than Authorized Persons (defined below); (c) not to use such Confidential Information except for the sole purpose of determining whether you (and not any other party) will enter into a business transaction with the Discloser (the “Purpose”).  For purposes of clarity, you may not disclose a Discloser’s Confidential Information to another party for the purpose of such party’s determining whether to enter into a business transaction with the Discloser, but only for the purpose of determining whether you will enter into a business transaction with the Discloser.  If any other party wishes to obtain access to any Confidential Information of a Discloser, such third party shall not have the right to obtain such information through you, and may be required to become a User of the Services and Site and to enter into this TOS in order to obtain access to such Confidential Information directly from the Discloser.  As used in this TOS, “Authorized Persons” means your accountants, attorneys, financial advisors, banks, and sources of financing who are bound by confidentiality obligations no less stringent than those in this Section 4.2 to maintain the confidentiality of Discloser’s Confidential Information and who need to have access to such Confidential Information for the Purpose.</p>

      <p><span className='green'>(ii)</span> In addition, you may disclose such Confidential Information if you are legally compelled to do so pursuant to a written court order, subpoena, regulatory demand, or process of law, provided that prior to any such compelled disclosure, you shall (a) unless prohibited by applicable law, promptly notify the Discloser of such compelled disclosure, (b) fully cooperate with the Discloser (at Discloser’s expense) in protecting against any such disclosure and/or obtaining a protective order narrowing the scope of such disclosure and/or use of the Confidential Information, and (c) solely disclose the portion of the Confidential Information compelled to be disclosed and solely to the party entitled to receive it.  Any such compelled disclosure shall not otherwise affect your obligations hereunder with respect to the Discloser’s Confidential Information so disclosed.</p>

      <p><span className='green'>(iii)</span> You agree that solely with respect to a Discloser’s Confidential Information, such Discloser shall be an intended third party beneficiary of this Section 4.2 of this TOS and shall have the right to enforce the terms of this Section 4.2 directly against you, without first requiring that Movie Funding take or join any action to enforce this Section 4.2 against you.  You also agree, as a Discloser of Confidential Information, that Movie Funding shall have the right in its sole discretion, but shall not have any obligation, to enforce this Section 4.2 against any Users to whom you provide your Confidential Information.  You agree that, due to the unique nature of the Confidential Information of Disclosers, the unauthorized disclosure or use of such Confidential Information will cause irreparable harm and significant injury to such Disclosers, the extent of which will be difficult to ascertain and for which there will be no adequate remedy at law.  Accordingly, you agree that Disclosers and Movie Funding, in addition to any other available remedies, shall have the right to seek an immediate injunction and other equitable relief enjoining any breach or threatened breach of your obligations under this Section 4.2 with respect to their Confidential Information, without the necessity of posting any bond or other security. </p> 

      <p><span className='green'>(iv)</span> You agree that at any time requested by the Discloser, you will destroy and permanently delete all Confidential Information of such Discloser (and all copies and extracts thereof) in your possession or control or as otherwise disclosed to Authorized Persons, and shall certify to such Discloser that you and your Authorized Persons have completed such destruction and deletion within ten (10) days after your receipt of request from such Discloser to so destroy and delete such Confidential Information.</p>
      <Disclaimer/>
    </div>
  )
}

